language: go

install:
  - go get github.com/InkProject/ink

script:
  - ink build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: public
  on:
    branch: master
